org.gradle.daemon=true
org.gradle.jvmargs=-Xmx3G
org.gradle.caching=true
org.gradle.parallel=true

mc_version=1.20.1
forge_version=47.3.10
parchment_mappings=2023.06.26

jei_version=15.20.0.104
rei_version=12.0.684
emi_version=1.1.10+1.20.1
cloth_config_version=11.1.118
top_version=10.0.1-3

kubejs_version=2001.6.3-build.47
rhino_version=2001.2.2-build.6
architectury_version=9.1.12