name: Release for 26.2.0

on:
  push:
    branches: [ '26.2.0' ]
  workflow_dispatch:

jobs:
  release:
    name: Publish release JAR for Ex Deorum
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[Release]') || github.event_name == 'workflow_dispatch'"
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Upload to CurseForge
        run: ./gradlew curseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Upload to Modrinth
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}